### ISSUE TITLE
Implement keybindings to build units

### ISSUE THREAD

**Issue by andy5995** [ZetaGlest/zetaglest-source#7]
When a building is selected, ability to press a key to build which unit is desired.

**Comment by Jammyjamjamman** [comment]
Implementing  system to select particular buildings using keys would be quite tricky, because there are different numbers of buildings for different factions (you could make one with no buildings). Also, would this assign numbers to buildings?

Another option is to create a build hotkey (but you still have to select the building). IMO if we do this, this is a a good first project.

**Comment by andy5995** [comment]
I often use control key grouping to select building.. When new obelisks are built, for instance, I add them to group 3.

So for this patch, I see it as.. I would press "3" to select my group, then Alt-1 to produce the first unit in the list. Alt-2 to produce the second unit in the list...

So.. somewhere in this codebase is an area where using a mouse click does that. I want to add the option to also select it with a hotkey combination.

**Comment by andy5995** [comment]
This is covered in #161
