### ISSUE TITLE
Ticket for ZetaGlest:  Helping Others Understand Windows Projects, a Document.

### ISSUE THREAD

**Issue by Joshei** [ZetaGlest/zetaglest-source#93]
Could we make quick brief on what each of the 8 Windows projects are for:   g2xml, g3d_viewer, glest_editor, glest_game, libglest, libstreflop, megaglest_tests, xml2g?  What they are, how they're useful and remarkable, how they interact, and anything else interesting.  I think it's important enough.

**Comment by Jammyjamjamman** [comment]
Where should this description be placed? in an `.md` file somewhere?

Anyway, here's a description of all of them:

* **g2xml** converts `.g3d` 3D zetaglest (and glest-relatives)  models into an xml formatted layout.

* **g2xml** converts `.xml`'s, in the layout specified  by **g2xml**, into `.g3d` 3D zetaglest (and glest-relatives)  models.

* **g3d_viewer** can be used to  `.g3d` 3D zetaglest (and glest-relatives) models.

*  **glest_editor** can be used to view zetaglest (and glest-relatives) maps in the `.gbm` and the `.mgm` format.

* `libglest`, `libstreflop` are libraries required to make zetaglest run.

* `megaglest_tests` contains software tests/ benchmarks for developers to use for when they modify some code. They are used to test the integrity of the zetaglest program.

I believe at this point in time, the `glest_game` directory has been removed from zetaglest.

**Comment by andy5995** [comment]
>I believe at this point in time, the glest_game directory has been removed from zetaglest

It's here. It contains the source code for the game part of the .. game.
https://github.com/ZetaGlest/zetaglest-source/tree/develop/source/glest_game

>Where should this description be placed? in an .md file somewhere?

I suggest the web site, and using .md files sparingly for documentation. md files can contain build instructions, contributing instructions.. Stuff related mostly to the development aspect.

There's probably no real need to split them up like that, but since we already have the md files present, probably no need to change either. Though one clear advantage is the md files are easier for multiple users to edit. So.. any problems with the Build instructions are more likely to get changed, etc.

As for *where* specifically on the web site.. not sure.. probably anyone could start a page, and then we could rearrange later.. if we want to make it a sub-category or something that wouldn't be hard to do. Something like this could be a subcategory/page of an FAQ section. Or perhaps just be added to an FAQ page.

**Comment by Jammyjamjamman** [comment]
>It's here. It contains the source code for the game part of the .. game. https://github.com/ZetaGlest/zetaglest-source/tree/develop/source/glest_game

Thanks for the info.

Hmm... It may be possible at some point to link the website pages to `.md` data... but that's another project ;-)

**Comment by andy5995** [comment]
Like here, where I linked to README.md, or did you mean something else?

https://zetaglest.github.io/docs/

And the "edit or improve this page" link will open up the github editor to edit the .sct (simplectemplate) file. The html page doesn't get updated until the next time someone runs src/simplecgen and pushes the changes, but I feel that having the "edit" link there improves the odds that people might add or edit.

**Comment by mathusummut** [comment]
The Windows Readme.md has been expanded to include this documentation.
